apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: opencost-cluster-prometheus
  namespace: {{ .Release.Namespace }}
spec:
  egress:
    - ports:
        - port: 9090
          protocol: TCP
      to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.caas.clusterPrometheusNamespace }}
          podSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus
  podSelector:
    matchLabels:
      app.kubernetes.io/name: prometheus
  policyTypes:
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: opencost-federation
  namespace: {{ .Values.caas.clusterPrometheusNamespace }}
spec:
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              field.cattle.io/projectId: {{ .Values.caas.projectId }}
  podSelector:
    matchLabels:
      app.kubernetes.io/name: prometheus
  policyTypes:
    - Ingress
