apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: opencost-prometheus
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - pods
      - endpoints
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: opencost-prometheus
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: opencost-prometheus
subjects:
  - kind: ServiceAccount
    name: opencost-prometheus-prometheus
    namespace: opencost
